### ISSUE TITLE
Project should be created in directory

### ISSUE THREAD

**Issue by Almad** [apiaryio/generator-apiary-lib#1]
Doing `mkdir` before is duplicit to entering project name, and leads to unexpected pollution of the pardir.

I'd add option to work in curdir, but wouldn't do it as default.

**Comment by honzajavorek** [comment]
The tool is meant to be used in curdir. Could you point me to where docs or code suggests elsewhere? Also, which `mkdir` do you mean?

**Comment by Almad** [comment]
> The tool is meant to be used in curdir.

Could that be documented, please?
