### ISSUE TITLE
Test command should run lint as well

### ISSUE THREAD

**Issue by XVincentX** [apiaryio/generator-apiary-lib#7]
...or the CI may pass with bad code!

**Comment by honzajavorek** [comment]
Pre-test runs `compile`, pre-compile runs `lint`. However, this is subject to discussion. I had conversations about what is the ideal point when linter should be ran, with both @Almad and @freaz. Options:

- Before test command. Current. Pros: You'll definitely produce nice code. Cons: Makes rapid prototyping very painful.
- Before commit. Pros: You'll definitely produce nice code. You can prototype without linter. Cons: Needs git hook installed locally, relies on developer.
- Before push. Pros: You'll produce nice code. You can prototype without linter. Cons: Needs git hook installed locally, relies on developer. May cause dedicated commits like "Fixed lint errors."
- Just on CI. Pros: You'll produce nice code. You can prototype without linter. Doesn't rely on developer, everyone faces the CI at the end. Cons: May cause dedicated commits like "Fixed lint errors."

I think CI brings the most benefits with the smallest trade-off.

**Comment by Almad** [comment]
> I think CI brings the most benefits with the smallest trade-off.

+1

> Cons: May cause dedicated commits like "Fixed lint errors."

`git rebase -i`, anyone?

**Comment by XVincentX** [comment]
I may be mistaking, but `eslint` is configurable in a way that, for example, when not in CI, we may treat all errors as warnings.

**Comment by honzajavorek** [comment]
Not sure. Scenario: My editor respects `eslint` rules as they are and I can see errors and I can ignore them myself if I want. When tests are ran, linter isn't summoned. When code is pushed to CI, the `circle.yml` (or similar) file contains both tests and linter. It could even run linter *after* tests, so the person knows everything is passing and all right, just linter errors need to be fixed. (This would be very annoying if your build is flaky and takes 40 minutes, but that can never happen, of course, especially with these small libraries ;-) ).

**Comment by honzajavorek** [comment]
Closing in favor of #17.
